server:
  port: 19003

eureka:
  client:
    service-url:
      defaultZone: http://eureka17001.com:17001/eureka,http://eureka17002.com:17002/eureka #集群版
spring:
  application:
    name: Cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Andrew-Yang999/MircoserviceDemo1.git
          search-paths:
            - Springcloud-config
          default-label: main
      label: main

