server:
  port: 19003

eureka:
  client:
    service-url:
      defaultZone: http://eureka17001.com:17001/eureka,http://eureka17002.com:17002/eureka #集群版
spring:
  application:
    name: Cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
            - springcloud-config
      label: master

