server:
  port: 18002
spring:
  application:
    name: Cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=utf-8&useSsl=false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0到1，1表示全采集
      probability: 1
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.andrew.entity.*Entity

eureka:
  client:
    service-url:
      defaultZone: http://eureka17001.com:17001/eureka,http://eureka17002.com:17002/eureka #集群版
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    instance-id: payment18002
