server:
  port: 18201
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.100:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: 'DEBUG'