server:
  port: 18801
spring:
  application:
    name: Cloud-consumer-order18801

eureka:
  client:
    service-url:
#      defaultZone: http://eureka17001.com:17001/eureka #单机版
      defaultZone: http://eureka17001.com:17001/eureka,http://eureka17002.com:17002/eureka #集群版
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    instance-id: order18801