server:
  port: 18204
spring:
  application:
    name: cloudalibaba-provicer-payment
  cloud:
    nacos:
      discovery:
        #        server-addr: 127.0.0.1:8848
        server-addr: 192.168.100.100:1111
management:
  endpoints:
    web:
      exposure:
        include: "*"